- README.md
Habe die Namen hinzugefügt. Okay für Dich, Bea?
> first stage

- .vscode-upload.json
- README.md
corrected headline to foobar
please review
> changed README.md Headline

- package-lock.json
- package.json
- src/main.js
Bitte überprüfen 
Dankeschön ^-^
> Install Pinia

- src/views/ImprintPage.vue
> docs: Added ImprintPage (Grundgerüst)

- src/views/FoundPage.vue
- src/views/LostPage.vue
> docs: Added LostPage, Added FoundPage

- src/views/ContactPage.vue
> code: added contact link to .vue

- src/views/UpdateLandingPage.vue
> code: build .vue UpdateLandingPage

- src/router/index.js
- src/views/ImpressumPage.vue
- src/views/LostPage.vue
> code: added .vue Impressum

- src/router/index.js
- src/views/FoundPage.vue
&& added Lost/Found-Pages in index.js ;)
> docs: added header pngs

- src/components/Landing.vue
- src/router/index.js
Buttons sind mit lost/found page connected
> Lostfound routing

- src/router/index.js
@BeaCoden bitte einmal gegenprüfen danke
> change: delete duplicate entries

- src/views/LostMatchMailPage.vue
> code: added send Btn

- src/views/AboutPage.vue
- src/views/ContactPage.vue
- src/views/FoundMessagePage.vue
- src/views/FoundPage.vue
- src/views/ImpressumPage.vue
- src/views/LostMatchMailPage.vue
- src/views/LostMatchPage.vue
- src/views/LostPage.vue
- src/views/LostnonMatchPage.vue
> code: added  & corrected footer links

- src/views/FoundMessagePage.vue
- src/views/LostMessagePage.vue
> rename .vue file & revise code

- package-lock.json
- package.json
- src/components/VueDatePicker.vue
- src/main.js
- src/views/FoundPage.vue
- src/views/LostPage.vue
Bitte überprüfen ;)
- evtl. kann man noch das heutige Datum als default adden.
> docs: added VueDatePicker in Lost/FoundPage

- src/stores/matchesStore.js
- src/views/FoundPage.vue
- src/views/LostPage.vue
> neuste stand

- src/views/FoundPage.vue
- src/views/LostPage.vue
> reviese code corrected Port Adress

- src/views/ContactPage.vue
> revise styling ContacPage

- src/components/VueDatePicker.vue
> docs: update Vue Date Picker

- package-lock.json
- package.json
- src/components/OpenLayersMap.vue
- src/main.js
- src/views/FoundPage.vue
Noch todo: Karte auf LostPage hinzufügen, sobald keiner mehr an dieser Seite arbeitet ;)
> docs: Karte auf FOUNDPage hinzugefügt
